projects:
  kraph:
    overwrite: true
    schema:
      "http://jhnnsrs-lab/kraph/schema":
        handleAsSDL: true
    documents: "graphql/kraph/**/*.graphql"
    generates:
      src/renderer/src/kraph/api/fragments.ts:
        plugins:
          - "fragment-matcher"
      src/renderer/src/kraph/api/graphql.ts:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typescript-react-apollo"
        config:
          withHooks: true
          reactApolloVersion: 3
          apolloReactHooksImportFrom: "@/lib/kraph/funcs"

      src/renderer/src/kraph/graphql.schema.json:
        plugins:
          - "introspection"
    extensions:
          endpoints:
            default:
              url: "http://jhnnsrs-lab/kraph/graphql"
              headers:
                Authorization: "Bearer ${API_TOKEN}"


